[package]
name = "finalApproach"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-actors = "4"
actix = "0.13"
rust-embed = "8"
mime_guess = "2"
serde_json = "1.0.140"
actix-cors = "0.7"
log = "0.4.27"
env_logger = "0.11.8"
